pipeline:
  install:
    image: node:10.19.0
    commands:
      - npm ci --unsafe-perm --quiet
    when:
      event: [push]

  lint:
    image: node:10.19.0
    commands:
      - git fetch origin master
      - FILES_CHANGED=$(git diff --name-only origin/master | grep '.js*$' || true)
      - npm run lint $FILES_CHANGED --unsafe-perm --quiet
    when:
      event: [push]

  test:
    image: node:10.19.0
    commands:
      - npm run test --bail --colors --silent
    when:
      event: [push]
